---
- name: Install
  ansible.builtin.apt:
    name: 
      - apache2
    update_cache: "yes"

- name: Start and enable apache2
  ansible.builtin.systemd:
    name: apache2
    state: started
    enabled: true
